version: '3'
services:
  mssql:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqlsystem:/var/opt/mssql
volumes:
  mssqlsystem:
    driver: local